######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 8 19:23:08 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += act_functions.h ad_thread.h mot_thread.h s3c2410-adc.h
FORMS += hef.ui
SOURCES += main.cpp
