#############################################################################
# Makefile for building: final_hefan
# Generated by qmake (2.01a) (Qt 4.4.0) on: ?? ??? 8 19:23:11 2016
# Project:  final_hefan.pro
# Template: app
# Command: /home/sprife/qt4/for_arm/qt-embedded-linux-opensource-src-4.4.0/bin/qmake -unix -o Makefile final_hefan.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/qws/linux-arm-g++ -I. -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtCore -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtCore -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtNetwork -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtNetwork -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtGui -I../../../nfs/Trolltech/qt-embedded-4.4.0/include/QtGui -I../../../nfs/Trolltech/qt-embedded-4.4.0/include -I. -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib
LIBS          = $(SUBLIBS)  -L/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib -lQtGui -L/home/sprife/qt4/for_arm/tslib-1.4-install/lib -L/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib -lts -lQtNetwork -lQtCore -lm -lrt -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = arm-linux-ranlib
QMAKE         = /home/sprife/qt4/for_arm/qt-embedded-linux-opensource-src-4.4.0/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp moc_act_functions.cpp \
		moc_ad_thread.cpp \
		moc_mot_thread.cpp
OBJECTS       = main.o \
		moc_act_functions.o \
		moc_ad_thread.o \
		moc_mot_thread.o
DIST          = ../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/qconfig.pri \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_functions.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_config.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_pre.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/release.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_post.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/warn_on.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/unix/thread.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/moc.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/resources.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/uic.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/yacc.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/lex.prf \
		final_hefan.pro
QMAKE_TARGET  = final_hefan
DESTDIR       = 
TARGET        = final_hefan

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_hef.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final_hefan.pro  ../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/qws/linux-arm-g++/qmake.conf ../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/qconfig.pri \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_functions.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_config.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_pre.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/release.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_post.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/warn_on.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/unix/thread.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/moc.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/resources.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/uic.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/yacc.prf \
		../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/lex.prf \
		/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtGui.prl \
		/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtNetwork.prl \
		/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile final_hefan.pro
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/qconfig.pri:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_functions.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt_config.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/exclusive_builds.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_pre.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/release.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/default_post.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/warn_on.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/qt.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/unix/thread.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/moc.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/resources.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/uic.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/yacc.prf:
../../../nfs/Trolltech/qt-embedded-4.4.0/mkspecs/features/lex.prf:
/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtGui.prl:
/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtNetwork.prl:
/mnt/nfs/Trolltech/qt-embedded-4.4.0/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile final_hefan.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/final_hefan1.0.0 || $(MKDIR) .tmp/final_hefan1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/final_hefan1.0.0/ && $(COPY_FILE) --parents act_functions.h ad_thread.h mot_thread.h s3c2410-adc.h .tmp/final_hefan1.0.0/ && $(COPY_FILE) --parents main.cpp .tmp/final_hefan1.0.0/ && $(COPY_FILE) --parents hef.ui .tmp/final_hefan1.0.0/ && (cd `dirname .tmp/final_hefan1.0.0` && $(TAR) final_hefan1.0.0.tar final_hefan1.0.0 && $(COMPRESS) final_hefan1.0.0.tar) && $(MOVE) `dirname .tmp/final_hefan1.0.0`/final_hefan1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/final_hefan1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_act_functions.cpp moc_ad_thread.cpp moc_mot_thread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_act_functions.cpp moc_ad_thread.cpp moc_mot_thread.cpp
moc_act_functions.cpp: ui_hef.h \
		mot_thread.h \
		ad_thread.h \
		s3c2410-adc.h \
		act_functions.h
	/mnt/nfs/Trolltech/qt-embedded-4.4.0/bin/moc $(DEFINES) $(INCPATH) act_functions.h -o moc_act_functions.cpp

moc_ad_thread.cpp: s3c2410-adc.h \
		ad_thread.h
	/mnt/nfs/Trolltech/qt-embedded-4.4.0/bin/moc $(DEFINES) $(INCPATH) ad_thread.h -o moc_ad_thread.cpp

moc_mot_thread.cpp: mot_thread.h
	/mnt/nfs/Trolltech/qt-embedded-4.4.0/bin/moc $(DEFINES) $(INCPATH) mot_thread.h -o moc_mot_thread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_hef.h
compiler_uic_clean:
	-$(DEL_FILE) ui_hef.h
ui_hef.h: hef.ui
	/mnt/nfs/Trolltech/qt-embedded-4.4.0/bin/uic hef.ui -o ui_hef.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ui_hef.h \
		act_functions.h \
		mot_thread.h \
		ad_thread.h \
		s3c2410-adc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_act_functions.o: moc_act_functions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_act_functions.o moc_act_functions.cpp

moc_ad_thread.o: moc_ad_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ad_thread.o moc_ad_thread.cpp

moc_mot_thread.o: moc_mot_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mot_thread.o moc_mot_thread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

